#!/bin/bash

# Get debugger working in Workbench:
sudo pacman -S yay
gpg --keyserver hkp://keys.gnupg.net:80 --recv-keys C52048C0C0748FEE227D47A2702353E0F7E48EDB
yay -S lib32-ncurses5-compat-libs

# Install particle packages
neopo install

# Complete particle-cli install and setup non-root USB access
neopo particle configure usb